version: '3.4'

services:
  litex:
    image: lerwys/litex
    container_name: litex
    stdin_open: true
    tty: true
    environment:
      - PATH=/opt/riscv32im/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/Xilinx/Vivado/2018.2/bin
    depends_on:
      - riscv-tools
    volumes:
      - type: volume
        source: riscv-tools-volume
        target: /opt/riscv32im
        volume:
          read_only: true
      - type: bind
        source: /opt/Xilinx
        target: /opt/Xilinx
        volume:
          read_only: true

  riscv-tools:
    image: lerwys/riscv-tools
    container_name: riscv-tools
    volumes:
      - type: volume
        source: riscv-tools-volume
        target: /opt/riscv32im
        volume:
          read_only: true

volumes:
  riscv-tools-volume:
